/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: loginUser

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/verify:
  controller: user
  action: verify

/forget:
  controller: user
  action: pwdforget

/dashboard:
  controller: admin
  action: dashboard
  security: 2
  childrens:
    /pages:
      controller: admin
      action: pages
