/:
  controller: main
  action: home

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: loginUser

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/verify:
  controller: user
  action: verify

/forget:
  controller: user
  action: pwdforget

/article:
  controller: article
  action: article

/dashboard:
  controller: admin
  action: dashboard
  security: 2

/pages-list:
  controller: page
  action: pagesList
  security: 1

/page-manager:
  controller: page
  action: pageManager
  security: 1

/medias-list:
  controller: media
  action: mediasList
  security: 1

/media-manager:
  controller: media
  action: mediaManager

/articles-list:
  controller: article
  action: articlesList
  security: 1

/article-manager:
  controller: article
  action: articleManager
  security: 1
