/:
  controller: main
  action: home

/install:
  controller: main
  action: install

/login:
  controller: user
  action: loginUser

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/me:
  controller: user
  action: me

/verify:
  controller: user
  action: verify

/forget:
  controller: user
  action: pwdforget

/reset:
  controller: user
  action: pwdReset

/article:
  controller: article
  action: frontView

/categories:
  controller: category
  action: categoriesView

/category:
  controller: category
  action: categoryView
/page:
  controller: page
  action: frontView

/dashboard:
  controller: admin
  action: dashboard
  security: 2

/pages-list:
  controller: page
  action: pagesList
  security: 1

/page-manager:
  controller: page
  action: pageManager
  security: 1

/medias-list:
  controller: media
  action: mediasList
  security: 2

/media-manager:
  controller: media
  action: mediaManager
  security: 2

/articles-list:
  controller: article
  action: articlesList
  security: 2

/article-manager:
  controller: article
  action: articleManager
  security: 2

/categories-list:
  controller: category
  action: categoriesList
  security: 2

/category-manager:
  controller: category
  action: categoryManager
  security: 2

/logs-view:
  controller: log
  action: logsShow
  security: 1

/users-list:
  controller: user
  action: usersList
  security: 1

/user-manager:
  controller: user
  action: userManager
  security: 1

# sitemap
/sitemap.xml:
  controller: main
  action: sitemap
